services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.4.1
    container_name: mealie-dev
    ports:
      - "9925:9000"
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - BASE_URL=http://localhost:9925
    volumes:
      - mealie-data:/app/data
    restart: unless-stopped

volumes:
  mealie-data:
